# Generated by Django 3.2 on 2021-05-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
