# Generated by Django 3.2 on 2021-05-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_camera_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='camera_video/'),
        ),
    ]
