# Generated by Django 3.2 on 2021-05-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_camera_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
