# Generated by Django 3.2 on 2021-05-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_alter_camera_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
