# Generated by Django 3.2 on 2021-05-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_alter_camera_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(blank=True, default='on', max_length=6, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='camera',
            name='active',
        ),
    ]
