# Generated by Django 3.2 on 2021-04-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='نام کتاب', max_length=50)),
                ('author', models.CharField(default='نویسنده', max_length=50)),
                ('Publisher', models.CharField(default='ناشر', max_length=50)),
                ('description', models.TextField(default='توضیحاتی ندارد')),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
