# Generated by Django 3.2 on 2021-04-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, default=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='image/Pottawatomie County State Lake #2 in Manhattan, KS.png', null=True, upload_to=''),
        ),
    ]
