# Generated by Django 3.2 on 2021-04-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Publisher',
            field=models.CharField(default='ناشر', max_length=50005),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='نویسنده', max_length=505),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='نام کتاب', max_length=505),
        ),
    ]
